sankey-beta
  Coal,Electricity,60
  Gas,Electricity,80
  Solar,Electricity,40
  Nuclear,Electricity,50
  Electricity,Homes,90
  Electricity,Industry,80
  Electricity,Transport,40
  Electricity,Losses,20
