import { describe, expect, it } from 'bun:test'
import { architectureToMermaidGraph, parseArchitectureDiagram } from '../architecture/parser.ts'
import { preprocessMermaidSource } from '../mermaid-source.ts'

function prep(text: string): string[] {
  return preprocessMermaidSource(text).lines
}

describe('parseArchitectureDiagram', () => {
  it('parses groups, services, junctions, and labeled edges', () => {
    const diagram = parseArchitectureDiagram(prep(`architecture-beta
      group edge(cloud)[Edge]
      group app(server)[Application]
      service api(server)[Public API] in app
      junction q in app
      service db(database)[Primary DB]
      api:R --> L:db
      api:B -[async]-> T:q`))

    expect(diagram.groups).toHaveLength(2)
    expect(diagram.services).toHaveLength(2)
    expect(diagram.junctions).toHaveLength(1)
    expect(diagram.edges).toHaveLength(2)

    expect(diagram.groups[1]!.children).toEqual([
      { kind: 'service', id: 'api' },
      { kind: 'junction', id: 'q' },
    ])

    expect(diagram.edges[1]).toEqual({
      source: { id: 'api', side: 'B', boundary: 'item' },
      target: { id: 'q', side: 'T', boundary: 'item' },
      label: 'async',
      hasArrowStart: false,
      hasArrowEnd: true,
    })
  })

  it('parses service group-boundary endpoints', () => {
    const diagram = parseArchitectureDiagram(prep(`architecture-beta
      group storage(cloud)[Storage]
      service db(database)[Database] in storage
      service cache(disk)[Cache]
      db{group}:R -[replicates]-> L:cache`))

    expect(diagram.edges[0]!.source.boundary).toBe('group')
    expect(diagram.edges[0]!.source.id).toBe('db')
    expect(diagram.edges[0]!.label).toBe('replicates')
  })

  it('preserves spaces inside edge labels', () => {
    const diagram = parseArchitectureDiagram(prep(`architecture-beta
      service api(server)[API]
      service db(database)[Database]
      api:R -[reads from]-> L:db`))

    expect(diagram.edges[0]!.label).toBe('reads from')
  })

  it('ignores comments and normalizes quoted multiline labels', () => {
    const diagram = parseArchitectureDiagram(prep(`---
config:
  theme: base
---
      %%{init: { "theme": "neutral" }}%%
      %% generated by docs
      architecture-beta
      %% keep this comment out of the parser
      group edge(cloud)[Edge<br/>Layer]
      service api(server)["Public<br/>API"] in edge
      service db(database)[Primary DB]
      api:R -["reads<br/>writes"]-> L:db`))

    expect(diagram.groups[0]!.label).toBe('Edge\nLayer')
    expect(diagram.services[0]!.label).toBe('Public\nAPI')
    expect(diagram.edges[0]!.label).toBe('reads\nwrites')
  })

  it('rejects group-boundary syntax on root services', () => {
    expect(() => parseArchitectureDiagram(prep(`architecture-beta
      service db(database)[Database]
      service api(server)[API]
      db{group}:R --> L:api`))).toThrow('is not inside a group')
  })

  it('parses accTitle and single-line accDescr', () => {
    const diagram = parseArchitectureDiagram(prep(`architecture-beta
      accTitle: System overview
      accDescr: Shows the main services and their connections
      service api(server)[API]`))

    expect(diagram.accessibilityTitle).toBe('System overview')
    expect(diagram.accessibilityDescription).toBe('Shows the main services and their connections')
    expect(diagram.services).toHaveLength(1)
  })

  it('parses multiline accDescr blocks', () => {
    const diagram = parseArchitectureDiagram(prep(`architecture-beta
      accTitle: Architecture
      accDescr {
        This diagram shows
        the system architecture
      }
      service api(server)[API]`))

    expect(diagram.accessibilityTitle).toBe('Architecture')
    expect(diagram.accessibilityDescription).toBe('This diagram shows\nthe system architecture')
  })

  it('rejects unterminated accDescr blocks', () => {
    expect(() => parseArchitectureDiagram(prep(`architecture-beta
      accDescr {
        Never closed
      service api(server)[API]`))).toThrow('Unclosed accDescr block')
  })

  // Upstream v11.16.0 (PR #7708): `align row|column <id> <id> ...` declares
  // that a set of already-declared services/junctions share a row (same y) or
  // column (same x). The plan's probe p8 class: these upstream-legal sources
  // must parse instead of hard-erroring as "Invalid architecture edge".
  it('parses a row alignment (upstream v11.16.0 align directive)', () => {
    const diagram = parseArchitectureDiagram(prep(`architecture-beta
      service src1(server)[Source 1]
      service src2(server)[Source 2]
      service src3(server)[Source 3]
      service proc(server)[Processor]
      src1:B --> T:proc
      src2:B --> T:proc
      src3:B --> T:proc
      align row src1 src2 src3`))

    expect(diagram.alignments).toEqual([{ axis: 'row', members: ['src1', 'src2', 'src3'] }])
    expect(diagram.services).toHaveLength(4)
    expect(diagram.edges).toHaveLength(3)
  })

  it('parses a column alignment with grouped services and junction members', () => {
    const diagram = parseArchitectureDiagram(prep(`architecture-beta
      group api(cloud)[API]
      service db1(database)[DB1] in api
      service db2(database)[DB2] in api
      junction j in api
      align column db1 db2 j`))

    expect(diagram.alignments).toEqual([{ axis: 'column', members: ['db1', 'db2', 'j'] }])
  })

  it('does not confuse align members with services whose id starts with row or column', () => {
    const diagram = parseArchitectureDiagram(prep(`architecture-beta
      service rowspan(server)[Rowspan]
      service columnar(server)[Columnar]
      align row rowspan columnar`))

    expect(diagram.services.map((service) => service.id)).toEqual(['rowspan', 'columnar'])
    expect(diagram.alignments).toEqual([{ axis: 'row', members: ['rowspan', 'columnar'] }])
  })

  it('rejects malformed align directives (upstream-parity negatives)', () => {
    const declared = `architecture-beta
      group g(cloud)[G]
      service a(server)[A]
      service b(server)[B]`

    // Axis must be row or column.
    expect(() => parseArchitectureDiagram(prep(`${declared}
      align diagonal a b`))).toThrow(/align/)
    // At least two members.
    expect(() => parseArchitectureDiagram(prep(`${declared}
      align row a`))).toThrow(/align/)
    // No duplicate members within one directive.
    expect(() => parseArchitectureDiagram(prep(`${declared}
      align row a a`))).toThrow(/align/)
    // Members must already be declared…
    expect(() => parseArchitectureDiagram(prep(`${declared}
      align row a ghost`))).toThrow(/ghost/)
    // …and must be services or junctions, never groups.
    expect(() => parseArchitectureDiagram(prep(`${declared}
      align row a g`))).toThrow(/group/)
  })

  it('converts architecture diagrams into graph layout input', () => {
    const graph = architectureToMermaidGraph(parseArchitectureDiagram(prep(`architecture-beta
      group platform(cloud)[Platform]
      service gateway(server)[Gateway] in platform
      service db(database)[Database]
      gateway:R --> L:db`)))

    expect(graph.nodes.get('gateway')!.shape).toBe('service')
    expect(graph.nodes.get('db')!.shape).toBe('service')
    expect(graph.subgraphs[0]!.id).toBe('platform')
    expect(graph.edges[0]!.source).toBe('gateway')
    expect(graph.direction).toBe('LR')
  })
})
